FROM ubuntu:latest

RUN apt update \ 
    && apt install -y nginx

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

COPY ./index.html /var/www/html/index.html

CMD [ "nginx", "-g", "daemon off;" ]
