FROM python:3.10.12-slim

COPY ./app /app
COPY ./requirements.txt .

RUN pip install -r requirements.txt

RUN apt update && \ 
    apt install -y curl

CMD [ "python", "-m", "app.main" ]

EXPOSE 8080
