version: "3"
services:
  web1: &web
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates
    port:
      - "80:80"
  web2:
    <<: *web
    port:
      - "81:80"
  web3:
    <<: *web
    port:
      - "82:80"
